name: test workflow

on:
  schedule:
    - cron: "5 * * * *" # runs at minute 5 of every hour
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
